const wordBank = [
  { lesson: 1, number: 1, word: "cooperate", meaning: "to work together" },
  { lesson: 1, number: 2, word: "kind", meaning: "being helpful" },
  { lesson: 1, number: 3, word: "pal", meaning: "a friend" },
  { lesson: 1, number: 4, word: "teacher", meaning: "a person who helps others learn" },
  { lesson: 1, number: 5, word: "student", meaning: "a person who studies" },
  { lesson: 1, number: 6, word: "classroom", meaning: "a place in school" },
  { lesson: 1, number: 7, word: "know", meaning: "to understand" },
  { lesson: 1, number: 8, word: "quiet", meaning: "not loud" },
  { lesson: 1, number: 9, word: "write", meaning: "to mark words" },
  { lesson: 1, number: 10, word: "read", meaning: "to take in words" },
  { lesson: 2, number: 1, word: "worried", meaning: "feeling uneasy" },
  { lesson: 2, number: 2, word: "glum", meaning: "sad" },
  { lesson: 2, number: 3, word: "brave", meaning: "ready to face danger" },
  { lesson: 2, number: 4, word: "laugh", meaning: "to smile and make sounds" },
  { lesson: 2, number: 5, word: "new", meaning: "not old" },
  { lesson: 2, number: 6, word: "best", meaning: "better than all others" },
  { lesson: 2, number: 7, word: "funny", meaning: "causing laughter" },
  { lesson: 2, number: 8, word: "play", meaning: "to be in  activities" },
  { lesson: 2, number: 9, word: "care", meaning: "to watch over" },
  { lesson: 2, number: 10, word: "share", meaning: "to give out" },
  { lesson: 3, number: 1, word: "tiny", meaning: "very small" },
  { lesson: 3, number: 2, word: "great", meaning: "very important" },
  { lesson: 3, number: 3, word: "gigantic", meaning: "huge" },
  { lesson: 3, number: 4, word: "garden", meaning: "a land for flowers" },
  { lesson: 3, number: 5, word: "grass", meaning: "a short green plant" },
  { lesson: 3, number: 6, word: "Earth", meaning: "a planet people live" },
  { lesson: 3, number: 7, word: "tree", meaning: "a plant with a long trunk" },
  { lesson: 3, number: 8, word: "vegetable", meaning: "a plant for food" },
  { lesson: 3, number: 9, word: "pond", meaning: "a small body of water" },
  { lesson: 3, number: 10, word: "insect", meaning: "a bug" },
  { lesson: 4, number: 1, word: "wise", meaning: "smart" },
  { lesson: 4, number: 2, word: "select", meaning: "to choose" },
  { lesson: 4, number: 3, word: "celebrate", meaning: "to do something special" },
  { lesson: 4, number: 4, word: "clap", meaning: "to hit your hands together" },
  { lesson: 4, number: 5, word: "call", meaning: "to say in a loud voice" },
  { lesson: 4, number: 6, word: "bang", meaning: "to hit loudly" },
  { lesson: 4, number: 7, word: "meow", meaning: "to make sound of a cat" },
  { lesson: 4, number: 8, word: "tell", meaning: "to give info" },
  { lesson: 4, number: 9, word: "say", meaning: "to express in words" },
  { lesson: 4, number: 10, word: "hear", meaning: "to receive sounds" },
  { lesson: 5, number: 1, word: "problem", meaning: "something that is difficult" },
  { lesson: 5, number: 2, word: "young", meaning: "an animal that was just born" },
  { lesson: 5, number: 3, word: "frightended", meaning: "very afraid" },
  { lesson: 5, number: 4, word: "dark", meaning: "having no light" },
  { lesson: 5, number: 5, word: "scare", meaning: "to frighten" },
  { lesson: 5, number: 6, word: "follow", meaning: "to go after" },
  { lesson: 5, number: 7, word: "behind", meaning: "at the back of" },
  { lesson: 5, number: 8, word: "appear", meaning: "to come into sight" },
  { lesson: 5, number: 9, word: "copy", meaning: "something that looks the same" },
  { lesson: 5, number: 10, word: "own", meaning: "belonging to oneself" },
  { lesson: 6, number: 1, word: "annoy", meaning: "to cause someone to feel angry" },
  { lesson: 6, number: 2, word: "tidy", meaning: "clean" },
  { lesson: 6, number: 3, word: "gather", meaning: "to come together" },
  { lesson: 6, number: 4, word: "give", meaning: "to hand something to somebody" },
  { lesson: 6, number: 5, word: "together", meaning: "in one group" },
  { lesson: 6, number: 6, word: "push", meaning: "to move" },
  { lesson: 6, number: 7, word: "join", meaning: "to bring together" },
  { lesson: 6, number: 8, word: "group", meaning: "things together" },
  { lesson: 6, number: 9, word: "help", meaning: "to do work for someone" },
  { lesson: 6, number: 10, word: "everyone", meaning: "every person" },
  { lesson: 7, number: 1, word: "adore", meaning: "to love very much" },
  { lesson: 7, number: 2, word: "bright", meaning: "smart" },
  { lesson: 7, number: 3, word: "confident", meaning: "believing you can do something well" },
  { lesson: 7, number: 4, word: "try", meaning: "to do something" },
  { lesson: 7, number: 5, word: "wish", meaning: "a hope for something" },
  { lesson: 7, number: 6, word: "reach", meaning: "to touch" },
  { lesson: 7, number: 7, word: "wait", meaning: "to stay in one place" },
  { lesson: 7, number: 8, word: "keep", meaning: "to save" },
  { lesson: 7, number: 9, word: "can", meaning: "to be able to" },
  { lesson: 7, number: 10, word: "goal", meaning: "end that a person wants" },
  { lesson: 8, number: 1, word: "sprint", meaning: "to run very fast" },
  { lesson: 8, number: 2, word: "fear", meaning: "to be afraid" },
  { lesson: 8, number: 3, word: "deliver", meaning: "to take something to a person" },
  { lesson: 8, number: 4, word: "bring", meaning: "to take" },
  { lesson: 8, number: 5, word: "fast", meaning: "moving with speed" },
  { lesson: 8, number: 6, word: "find", meaning: "to discover" },
  { lesson: 8, number: 7, word: "lift", meaning: "to raise" },
  { lesson: 8, number: 8, word: "pick", meaning: "to choose" },
  { lesson: 8, number: 9, word: "ride", meaning: "to be carried by a car or aninmal" },
  { lesson: 8, number: 10, word: "take", meaning: "to carry" },
  { lesson: 9, number: 1, word: "curious", meaning: "eager to understand more" },
  { lesson: 9, number: 2, word: "wonder", meaning: "to think about" },
  { lesson: 9, number: 3, word: "describe", meaning: "to tell about something" },
  { lesson: 9, number: 4, word: "cold", meaning: "not hot" },
  { lesson: 9, number: 5, word: "cool", meaning: "a little cold" },
  { lesson: 9, number: 6, word: "warm", meaning: "a little hot" },
  { lesson: 9, number: 7, word: "wet", meaning: "having water" },
  { lesson: 9, number: 8, word: "dry", meaning: "not wet" },
  { lesson: 9, number: 9, word: "soft", meaning: "not hard" },
  { lesson: 9, number: 10, word: "hard", meaning: "firm" },
  { lesson: 10, number: 1, word: "peaceful", meaning: "quiet and calm" },
  { lesson: 10, number: 2, word: "confused", meaning: "unable to understand" },
  { lesson: 10, number: 3, word: "frosty", meaning: "very cold" },
  { lesson: 10, number: 4, word: "sled", meaning: "a now vehicle" },
  { lesson: 10, number: 5, word: "snow", meaning: "the frozen water" },
  { lesson: 10, number: 6, word: "winter", meaning: "season after autumn" },
  { lesson: 10, number: 7, word: "lazy", meaning: "not wanting to work" },
  { lesson: 10, number: 8, word: "fireplace", meaning: "an open space for fire" },
  { lesson: 10, number: 9, word: "scarf", meaning: "cloth for the neck" },
  { lesson: 10, number: 10, word: "mittens", meaning: "gloves with two parts" },
  { lesson: 11, number: 1, word: "fair", meaning: "not favoring someone" },
  { lesson: 11, number: 2, word: "amazing", meaning: "surprising and wonderful" },
  { lesson: 11, number: 3, word: "greedy", meaning: "wanting more" },
  { lesson: 11, number: 4, word: "wake", meaning: "to stop sleeping" },
  { lesson: 11, number: 5, word: "morning", meaning: "the earliest part of the day" },
  { lesson: 11, number: 6, word: "eat", meaning: "to put food in your body" },
  { lesson: 11, number: 7, word: "drink", meaning: "to put drinks in your body" },
  { lesson: 11, number: 8, word: "afternoon", meaning: "12PM~5PM" },
  { lesson: 11, number: 9, word: "wash", meaning: "to clean" },
  { lesson: 11, number: 10, word: "dinner", meaning: "a meal at night" }
];
